### ISSUE TITLE
Pressing "z" results in blank view

### ISSUE THREAD

**Issue by chufucious** [seenaburns/isolate#20]
Isolate v2

When the nav bar is closed and I press `z` I get a blank screen and am unable to exit or navigate away. Quitting and reopening fixes the problem.

**Comment by seenaburns** [comment]
Fixed in 1f5e3d7, long term this should be addressed by moving the key handler to a reducer, so the state when a key is pressed can be checked.

**Comment by seenaburns** [comment]
Cut a new release https://github.com/seenaburns/isolate/releases/tag/v2.0.1 hopefully this should fix it, but let me know if not and I can pursue the more correct solution.

Thanks for the incredibly fast, clear and reproducible bug report 🙏 it doesn't get any better than that!

**Comment by chufucious** [comment]
Fixed! Thanks 👍
