### ISSUE TITLE
Will GIFs be supported in a later release?

### ISSUE THREAD

**Issue by zuggamasta** [seenaburns/isolate#3]
Hi,

_I do not want to directly request this._ I was just interessted if there will be the possibility 
to also browse *.gif files, either animated or just the first frame of each file.

Thank you for sharing this nice tool with the world!

Alex

**Comment by seenaburns** [comment]
You got it! Added in b170662d023d102f1a38806ca320d608642d8855 and just cut a new release https://github.com/seenaburns/isolate/releases/tag/v1.0.1

It'd be nice to pause all gifs, especially for gif heavy folders but for now I removed the artificial restriction to not include gifs (or svg's)
