### ISSUE TITLE
Antivirus false-flag?

### ISSUE THREAD

**Issue by Ravneson** [seenaburns/isolate#4]
Just downloaded the "isolate.1.0.0.exe" release & BitDefender flagged the download as infected by "Generic.Malware.FM!.8C4530F8", I'm guessing this is a false flag by the AV software, but might be others than me as well that have this issue.

**Comment by GitSquared** [comment]
Two cents on this:

Happens on all Electron apps when their build is unsigned. I wonder if @seenaburns will spend the cash for a certificate (unlikely IMO, stuff ain't cheap). False positive anyway, just tell your AV to f*** off.

**Comment by seenaburns** [comment]
@GitSquared thank you for the context, this is pretty unfortunate but I don't think I want to pursue shelling out for a certificate right now =/

**Comment by GitSquared** [comment]
@seenaburns perhaps if enough people use the binary it will be unflagged anyway. Or you could try to submit it directly to AVs... Might not be worth the effort to be honest. Your call. o/

**Comment by Ravneson** [comment]
Good to know! 1.0.1 didn't seem to trigger the AV this time around, so all good here (loving isolate!)

**Comment by seenaburns** [comment]
Closing but can reopen if others have problems in the future
