### ISSUE TITLE
Image order in rows?

### ISSUE THREAD

**Issue by vorg** [seenaburns/isolate#7]
Are images ordered in columns not rows? Is that planned / expected?
 
```
//current
1 4 7
2 5 8
3 6 9

//what I would expect
1 2 3
4 5 6
7 8 9
```

**Comment by seenaburns** [comment]
Agreed this is an annoyance. When I looked into these "masonry layouts" there isn't a solution to do it in terms of pure css without knowing the image dimensions up front.

There's one avenue of trying to detect image dimension upfront (solutions I've seen read the file into memory first), and another of using javascript to create the layout. I've found the latter to be pretty perf expensive, and every time you resize the window it has to be recomputed.

I'm not super thrilled about either of these, but maybe it's something that can be exposed as an option.

**Comment by vorg** [comment]
Yeah, i’m using JS in https://github.com/vorg/kollektor. I’ve been working on no-database mode where you can fire it from any folder and had similar problem of not knowing file size in advance. I’m experimenting with “assume all images are square” for columns assingment and while they dont end up with the same height its often a good approximation.

**Comment by seenaburns** [comment]
@vorg I ended up going with your suggestion! The columns don't end up even (can be pretty off) but it both gives the expected ordering and lets chrome layout images without having to load them all for the dimensions (previously it was loading top to bottom, left to right, which was perceptually really jarring)
